---
title: "Library Resources"
format: html
---

#### **Resource List**

This is the Library’s online reading list tool. It links to any Resource List associated with this course and provides access to key readings. If you would like some guidance on using your Resource List, have a look at this [video](https://edin.ac/Resource-Lists-student-video) 

#### **Subject Guide**

Subject Guides help you get the best out of the Library with information on finding academic literature, referencing and more.

-   [Medicine Subject Guide](https://edinburgh-uk.libguides.com/medicine)

-   [Literature review & study skills resources for intercalating medical students Subject Guide](https://edinburgh-uk.libguides.com/c.php?g=668801)

#### **DiscoverEd**

Use [DiscoverEd](https://discovered.ed.ac.uk/) to search the Library's collections and find books, ebooks, ejournal articles and more. Use your University login to sign into your account and manage loans, requests and fines.

#### **InterLibrary Loans (ILL)**

If the University of Edinburgh does not hold the material you need, you can use the InterLibrary Loans (ILL) service to request access to resources held in other libraries. Use the link, 'InterLibrary Loan Request' at the top of DiscoverEd. [More information about ILL](https://edin.ac/interlibrary_loans) 

#### **Request a Book (RaB)**

You can use the Library’s Request a Book (RaB) service to request purchase of books and other resources to be added to the Library collections to support your University study and research. [More information about RaB](https://edin.ac/request_a_book) 

#### **Scan & Deliver**

This is the Library’s scan on demand service. Scan & Deliver provides scans of chapters or extracts of print items held at all University of Edinburgh Libraries (copyright restrictions apply). Use DiscoverEd to make a request. [More information about Scan & Deliver](https://edin.ac/scan_and_deliver)   
