project:
  type: website
  output-dir: "./docs"
  post-render: encrypt.R
  preview:
    port: 5133

website:
  title: "Data Science for Health and Biomedical Sciences"
  navbar:
    pinned: true
    background: "#2a405e"
    right:
        - text: "Content"
          file: content/index.qmd
        - text: "Assignment"
          file: assignment/index.qmd

format:
  html:
    theme: 
      - litera
      - custom.scss
    toc: true
    hihghlight-style: monokai

editor: visual

