project:
  type: website
  output-dir: "./docs"
  post-render: encrypt.R
  render:
    - "*.qmd"
    - "!tutorials/" # Exclude the entire 'tutorials' folder from rendering
  preview:
    port: 5133

execute:
  freeze: auto

website:
  title: "Data Science for Health and Biomedical Sciences"
  description: "The course aims to provide a broad introduction to data science in health and biomedical sciences, covering key concepts and principles, data analysis skills and implications of working with biomedical and healthcare data."
  site-url: "https://ddi-talent.github.io/website-ug-data-science/"
  favicon: "/favicon.png"
  navbar:
    pinned: true
    background: "#2a405e"
    right:
        - text: "Course Information"
          menu:
            - text: "Welcome and Learning Outcomes"
              file: course-information/welcome.qmd
            - text: "Course Information"
              file: course-information/index.qmd
            - text: "Timetable"
              file: course-information/timetable.qmd
            - text: "Library Resources"
              file: course-information/library-resources.qmd
            - text: "Course Contacts"
              file: course-information/course-contacts.qmd
            - text: "Gen AI Guidance"
              file: course-information/gen-ai-guidance.qmd
            - text: "Help and Support"
              file: course-information/help-and-support.qmd
        - text: "Content"
          file: content/index.qmd
        - text: "Assessment"
          file: assessment/index.qmd
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      collapse-level: 1
      contents:
        - section: "Content"
          contents:
            - content/index.qmd
        - section: "Week 1: Introduction"
          contents:
            - content/week-1/index.qmd
            - text: "Topic 1: Introduction to Health Data Science"
              file: content/week-1/topic-1.qmd
            - text: "Topic 2: The Role of Ethics in Health and Social Care"
              file: content/week-1/topic-2.qmd
            - text: "Topic 3: Getting started with R"
              file: content/week-1/topic-3.qmd
            - text: "Topic 4: Types of Health Data"
              file: content/week-1/topic-4.qmd
            - text: "Topic 5: Guide to R Markdown"
              file: content/week-1/topic-5.qmd
            - text: "Topic 6: Troubleshooting and Error Messages"
              file: content/week-1/topic-6.qmd
            - text: "Further Optional Resources"
              file: content/week-1/further-resources.qmd
            - text: "Tutorial materials"
              file: content/week-1/tutorial.qmd
              
        - section: "Week 2: Data Tidying and Wrangling"
          contents:
            - content/week-2/index.qmd
            - text: "Topic 1: The Tidyverse"
              file: content/week-2/topic-1.qmd
            - text: "Topic 2: Importing Data"
              file: content/week-2/topic-2.qmd
            - text: "Topic 3: Exploring data"
              file: content/week-2/topic-3.qmd
            - text: "Topic 4: Ethical Dilemmas in Health Care Data"
              file: content/week-2/topic-4.qmd
            - text: "Topic 5: Files and Folders"
              file: content/week-2/topic-5.qmd
     
format:
  html:
    theme: 
      - litera
      - custom.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual

