project:
  type: website
  output-dir: docs
  post-render: encrypt.R

website:
  title: "Data Science for Health and Biomedical Sciences"
  navbar:
    left:
      - text: Content
        menu: 
          - week-1.qmd
          - week-2.qmd
          - week-3.qmd
          - week-4.qmd
          - week-5.qmd
          - week-6.qmd
          - week-7.qmd
          - week-8.qmd
          - week-9.qmd
          - week-10.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

