project:
  type: website
  output-dir: "./docs"
  #post-render: encrypt.R
  preview:
    port: 5133

website:
  title: "Data Science for Health and Biomedical Sciences"
  description: "The course aims to provide a broad introduction to data science in health and biomedical sciences, covering key concepts and principles, data analysis skills and implications of working with biomedical and healthcare data."
  site-url: "https://ddi-talent.github.io/website-ug-data-science/"
  navbar:
    pinned: true
    background: "#2a405e"
    right:
        - text: "Course Information"
          menu:
            - text: "Welcome and Learning Outcomes"
              file: course-information/welcome.qmd
            - text: "Course Information"
              file: course-information/index.qmd
            - text: "Timetable"
              file: course-information/timetable.qmd
            - text: "Library Resources"
              file: course-information/library-resources.qmd
        - text: "Content"
          file: content/index.qmd
        - text: "Assignment"
          file: assignment/index.qmd
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      collapse-level: 1
      contents:
        - section: "Content"
          contents:
            - content/index.qmd
        - section: "Week 1: Introduction"
          contents:
            - content/week-1/index.qmd
            - text: "Topic 1"
              file: content/week-1/topic-1.qmd
            - text: "Topic 2"
              file: content/week-1/topic-2.qmd
        - section: "Week 2: Data Tidying and Wrangling"
          contents:
            - content/week-2/index.qmd
            - text: "Topic 1"
              file: content/week-2/topic-1.qmd
            - text: "Topic 2"
              file: content/week-2/topic-2.qmd
     
format:
  html:
    theme: 
      - litera
      - custom.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual

