project:
  type: website
  output-dir: "./docs"
  post-render: encrypt.R
  render:
    - "*.qmd"
    - "!tutorials/" # Exclude the entire 'tutorials' folder from rendering
  preview:
    port: 5133

execute:
  freeze: auto

website:
  title: "Data Science for Health and Biomedical Sciences"
  description: "The course aims to provide a broad introduction to data science in health and biomedical sciences, covering key concepts and principles, data analysis skills and implications of working with biomedical and healthcare data."
  site-url: "https://ddi-talent.github.io/website-ug-data-science/"
  favicon: "/favicon.png"
  navbar:
    pinned: true
    background: "#2a405e"
    right:
        - text: "Course Information"
          menu:
            - text: "Welcome and Learning Outcomes"
              file: course-information/welcome.qmd
            - text: "Course Information"
              file: course-information/index.qmd
            - text: "Timetable"
              file: course-information/timetable.qmd
            - text: "Library Resources"
              file: course-information/library-resources.qmd
            - text: "Course Contacts"
              file: course-information/course-contacts.qmd
            - text: "Gen AI Guidance"
              file: course-information/gen-ai-guidance.qmd
            - text: "Help and Support"
              file: course-information/help-and-support.qmd
        - text: "Content"
          file: content/index.qmd
        - text: "Assessment"
          file: assessment/index.qmd
              
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      collapse-level: 1
      contents:
        - section: "Content"
          contents:
            - content/index.qmd
        - section: "Week 1: Introduction"
          contents:
            - content/week-1/index.qmd
            - text: "Topic 1: Introduction to Health Data Science"
              file: content/week-1/topic-1.qmd
            - text: "Topic 2: The Role of Ethics in Health and Social Care"
              file: content/week-1/topic-2.qmd
            - text: "Topic 3: Getting started with R"
              file: content/week-1/topic-3.qmd
            - text: "Topic 4: Types of Health Data"
              file: content/week-1/topic-4.qmd
            - text: "Topic 5: Guide to R Markdown"
              file: content/week-1/topic-5.qmd
            - text: "Topic 6: Troubleshooting and Error Messages"
              file: content/week-1/topic-6.qmd
            - text: "Further Optional Resources"
              file: content/week-1/further-resources.qmd
            - text: "Tutorial materials"
              file: content/week-1/tutorial.qmd
              
        - section: "Week 2: Data Tidying and Wrangling"
          contents:
            - content/week-2/index.qmd
            - text: "Topic 1: The Tidyverse"
              file: content/week-2/topic-1.qmd
            - text: "Topic 2: Importing Data"
              file: content/week-2/topic-2.qmd
            - text: "Topic 3: Exploring Data"
              file: content/week-2/topic-3.qmd
            - text: "Topic 4: Ethical Dilemmas in Health Care Data"
              file: content/week-2/topic-4.qmd
            - text: "Topic 5: Files and Folders"
              file: content/week-2/topic-5.qmd
            - text: "Tutorial materials"
              file: content/week-2/tutorial.qmd
          
        - section: "Week 3: Data Visualisation and Storytelling"
          contents:
            - content/week-3/index.qmd
            - text: "Topic 1: Data Visualisation"
              file: content/week-3/topic-1.qmd
            - text: "Topic 2: Data visualisation aims"
              file: content/week-3/topic-2.qmd
            - text: "Topic 3: Data Storytelling"
              file: content/week-3/topic-3.qmd
            - text: "Topic 4: Plotting data with ggplot2"
              file: content/week-3/topic-4.qmd
            - text: "Topic 5: Going Further with R Markdown"
              file: content/week-3/topic-5.qmd
            - text: "Topic 6: More Wrangling and Plotting"
              file: content/week-3/topic-6.qmd
            - text: "Topic 7: Introduction to GitHub"
              file: content/week-3/topic-7.qmd
            - text: "Tutorial materials"
              file: content/week-2/tutorial.qmd
            - text: "Setting up repos for use with RStudio"
              file: content/week-3/version-controlled-projects.qmd
              
        - section: "Week 4: Analysing and Presenting Data in R"
          contents:
            - content/week-4/index.qmd
            - text: "Topic 1: Wrangling factors and joins"
              file: content/week-4/topic-1.qmd
            - text: "Topic 2: Fine-tuning plots"
              file: content/week-4/topic-2.qmd
            - text: "Topic 3: Roundup and recap"
              file: content/week-4/topic-3.qmd
            - text: "Optional: Data Engagements & Data Controversies"
              file: content/week-4/data-engagements-and-controversies.qmd
            - text: "Tutorial materials"
              file: content/week-4/tutorial.qmd
              
        - section: "Week 5: Making Maps and Tables in R"
          contents:
            - content/week-5/index.qmd
            - text: "Topic 1: Introduction to Geospatial Data in R with sf and Tidyverse"
              file: content/week-5/topic-1.qmd
            - text: "Topic 2: Creating more exciting tables"
              file: content/week-5/topic-2.qmd
            - text: "Optional: Writing Functions in R"
              file: content/week-5/writing-functions-in-R.qmd
            - text: "Tutorial materials"
              file: content/week-5/tutorial.qmd
            - text: "Optional: Writing Functions in R"
              file: content/week-5/writing-functions-in-R.qmd
              
        - section: "Week 6: Machine Learning & Analysing Clinical Text"
          contents:
            - content/week-6/index.qmd
            - text: "Topic 1: Machine Learning"
              file: content/week-6/topic-1.qmd
            - text: "Topic 2: Analysing Clinical Text"
              file: content/week-6/topic-2.qmd
            - text: "Topic 3: Embedding Ethics into Data Sharing"
              file: content/week-6/topic-3.qmd
            - text: "Tutorial materials"
              file: content/week-6/tutorial.qmd
              
        - section: "Week 7: Improving Healthcare Processes & Integrating Health Data"
          contents:
            - content/week-7/index.qmd
            - text: "Topic 1: Computational Methods for Improving Healthcare Processes"
              file: content/week-7/topic-1.qmd
            - text: "Topic 2: Integrating Health Data"
              file: content/week-7/topic-2.qmd
            - text: "Topic 3: Improving Healthcare Processes"
              file: content/week-7/topic-3.qmd
            - text: "TBC: Optional: NHS R - modelling hospital flow"
              file: content/week-7/optional-nhs-r-modelling.qmd
            - text: "Tutorial materials"
              file: content/week-7/tutorial.qmd
          
        - section: "Week 8: Data and Identity"
          contents:
            - content/week-8/index.qmd
            - text: "Data and Identity - readings"
              file: content/week-8/readings.qmd
            - text: "Guest lecture slides"
              file: content/week-8/guest-lecture-slides.qmd
          
        - section: "Week 9: Data Ownership"
          contents:
            - content/week-9/index.qmd
            - text: "Reading: COVID and cause of death"
              file: content/week-9/readings.qmd
            - text: "Visibility of What?"
              file: content/week-9/visibility-of-what-slides.qmd
            - text: "Guest lecture slides"
              file: content/week-9/guest-lecture-slides.qmd
              
        - section: "Week 10: Working with Genomic Data"
          contents:
            - content/week-10/index.qmd
            - text: "Topic 1: Genomic data: What is it and how to analyse it"
              file: content/week-10/topic-1.qmd
            - text: "Topic 2: Genotyping, sequencing, and profiling"
              file: content/week-10/topic-2.qmd
            - text: "Topic 3: Genome-wide association studies"
              file: content/week-10/topic-3.qmd
            - text: "Topic 4:GWAS Resources"
              file: content/week-10/topic-4.qmd
            - text: "Tutorial materials"
              file: content/week-10/tutorial.qmd
        
    - title: "Assessment"
      contents:
        - section: "Overview"
          contents:
            - assessment/index.qmd
        - section: "ICA1 - R Programming Assignment"
          contents:
            - text: "Formative assessment"
              file: assessment/formative-assessment.qmd
            - text: "Assessment Brief and Rubric"
              file: assessment/assessment-brief-and-rubric.qmd
        - section: "ICA2 - Essay"
          contents:
            - text: "Assessment and Submission Details"
              file: assessment/assessment-and-submission-details.qmd
            - text: "ICA Cover Sheet"
              file: assessment/ica2-cover-sheet.qmd
              
     
format:
  html:
    theme: 
      - litera
      - custom.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual

