---
title: "Welcome!"
---

In this course you will be introduced to data science techniques used in health and biomedicine, you'll have a chance to practice these techniques in R, and you'll learn about the social and societal issues surrounding the increased use of data science in human health. The course will be taught in a flipped classroom format: each week, you will be given a set of videos and readings to go through at home, and in the live sessions on Thursdays and Fridays we'll discuss and practice what you learned from those materials. It is therefore crucial that you do complete the required preparation work before class; otherwise, you will not be able to fully participate.

The course materials have been prepared for you by various staff from the Usher Institute and the wider College of Medicine and Veterinary Medicine. The two weeks focused on data ethics will be delivered in collaboration with two experts in this topic: Dr Kevin Guyan from the Business School and Dr Max Perry from the School of Social and Political Science.

We look forward to working with you!

## Learning Outcomes

{{< fa thumbs-up >}} 
{{< fa folder >}}
{{< fa chess-pawn >}}
{{< fa brands bluetooth >}}
{{< fa brands twitter size=2xl >}}
{{< fa brands github size=5x >}}
{{< fa battery-half size=Huge >}}
{{< fa envelope title="An envelope" >}}

On successful completion of this course, you should be able to:

-   Apply a range of specialised data science techniques to different medical and healthcare scenarios.

-   Analyse health and biomedical data with the use of the R programming language, including summarisation, visualisation and interpretation.

-   Critically examine the ethical, societal and regulatory principles and implications of data science in health.

-   Explain and critically discuss key concepts, principles and methods of data science in health.

```{r eval = FALSE}
1 + 1
```
