---
title: "Readings, videos and exercises"
format: html
---

Each week, you will be given a set of readings, videos and exercises to complete. These are designed to help you understand the material and to prepare you for the tutorials and assignment.

In-person tutorials will be held on Thursday and Friday afternoons from 2-5pm. During the tutorials you will work in pairs to complete coding exercises together. This is called **pair programming** and is an effective and fun way to learn to code. The tutorials are an important part of the course and you are expected to attend.

It is important to complete the material before the tutorials, as the exercises will build on the material covered in the videos and readings. The tutorials will be a chance to ask questions and to get help with the exercises.

## {{< fa question >}} Quiz

There will be a quiz at the beginning of each tutorial to informally test your understanding of the material and discuss in your pairs.

## {{< fa book >}} Homework

On some weeks, there will be a homework exercise that you can complete on your own for practice. These won't be marked, but they will be a good way to practice the material and to prepare for the assignment.

**Note: The content will be released weekly**

## Weekly Topics:

{{< fa calendar >}} **Week 1**: Introduction

{{< fa calendar >}} **Week 2**: Data Tidying and Wrangling

{{< fa calendar >}} **Week 3**: Data Visualisation and Storytelling

{{< fa calendar >}} **Week 4**: Analysing & Presenting Data in R

{{< fa calendar >}} **Week 5**: Maps, tables, functions

{{< fa calendar >}} **Week 6**: Machine Learning & Analysing Clinical Tests

{{< fa calendar >}} **Week 7**: Improving Healthcare Processes & Integrating Health Data

{{< fa calendar >}} **Week 8**: Data and Identity

{{< fa calendar >}} **Week 9**: Data Ownership

{{< fa calendar >}} **Week 10**: Working with Genomic Data
