---
title: "Machine Learning"
format: html
---

## Machine Learning

**Overview**

What is machine learning, what can it do and what can it not do for biomedicine and healthcare? In this topic you will be introduced to two main types of machine learning, i.e. supervised and unsupervised learning, you will find out about some recent success in using machine learning methods in health, and you will learn how it relates to artificial intelligence and other topics covered in this course.

### **Supervised and Unsupervised Learning**

Watch the following 4 videos to find out what machine learning is, and what methods are used in supervised and unsupervised learning for health.

<https://media.ed.ac.uk/media/1_kd30g0to>

<https://media.ed.ac.uk/media/0_0o96pa11>

<https://media.ed.ac.uk/media/1_l42iag3e>

<https://media.ed.ac.uk/media/1_w35wwarn>

INCLUDE THE DOCS HERE!

### **Case Study of Machine Learning in Medicine**

One of the biggest success stories of machine learning in healthcare involves the use of **deep learning methods for diagnosis and referral in retinal disease**, which was the result of a collaboration between Moorfields Eye Hospital NHS Foundation Trust, the UCL Institute of Ophthalmology and DeepMind Health. Researchers from these organisations worked together to apply a novel deep learning architecture to a set of thousands of historic de-personalised OCT eye scans to identify signs of eye disease and recommend how patients should be referred for care. The results, which were published online in [Nature Medicine](https://doi.org/10.1038/s41591-018-0107-6), show that the AI system can recommend the correct referral decision for over 50 eye diseases with 94% accuracy, matching world-leading eye experts. This high level of accuracy is a major breakthrough, and shows great potential for helping doctors spot conditions earlier and quickly prioritise patients who need urgent treatment.

It is still early days, however, and the next step is to go through clinical trials to explore how this technology might improve patient care in practice, and regulatory approval before it can be used in hospitals and other clinical settings.

*Reading based on content on [Moorfields Eye Hospital website](https://www.moorfields.nhs.uk/content/breakthrough-ai-technology-improve-care-patients), where one can find further information and videos.*

### **Artificial Intelligence is more than Machine Learning**

The term "Artificial Intelligence" is sometimes used as a synonym for Machine Learning. However, **Artificial Intelligence (AI) is a much broader field than Machine Learning (ML)**. This reading aims to demystify what AI is and how it relates to ML.

In their seminal book \"Artificial Intelligence: A Modern Approach\", Russell and Norvig explain that there are four approaches or types of definitions for AI:

-   **Systems that act like humans**: The authors describe this as \"the Turing Test approach\", and they point out that a machine would need to possess a range of capabilities, including among others: natural language processing, to allow successful communication in English or some other human language; computer vision, to perceive objects; and robotics, to manipulate objects and move around.

-   **Systems that think like humans:** This is the cognitive modelling approach to AI, where essentially we\'re trying to get inside the actual working of human mind and then replicate this in a machine. In order to construct precise and testable theories of the workings of the human mind, the interdisciplinary field of cognitive science brings together computer models from AI and experimental techniques from psychology.

-   **Systems that think rationally:** This is the "laws of thought" approach, where we create intelligent systems by making precise statements about all kinds of things in the world and about the relations among them. In order to make these statements and make inferences based on them, the field of logic is typically used, tracing all the way back to the Greek philosopher Aristotle.

-   **Systems that act rationally:** This is the "rational agent" approach to AI. A computer agent is more than just a computer program, in the sense that it can operate under autonomous control, perceive its environment, adapt to changes, take on another\'s goals, etc. A rational agent is one that acts with the objective to achieve the best possible outcome.

When looking at the history of AI (it all started in the 50s!), one can identify two key eras or schools of thought. The first era (between the 1950s and late 1980s), which is also referred to as **symbolic AI** or "good old-fashioned AI", was dominated by the logic-based or rule-based approach. Expert systems were a prominent technology at the time, capturing facts and rules about the world, and deducing new information. MYCIN was one of the most influential medical expert systems during that era, and it was designed to identify bacteria causing severe infections, such as bacteremia and meningitis, and to recommend antibiotics, with the dosage adjusted for the patient's body weight. The first era of AI ended with a so-called "AI winter" around the early 90s.

We are currently undergoing the second era or "spring" of AI, where **machine learning** is the main area of focus. This is not only because of recent advances in computational methods and algorithms, but perhaps more importantly because of the vast amounts of data that are now available for training machine learning systems. Machine learning methods are used across different areas and topics discussed in this course, such as medical imaging and natural language processing.

### **Distinguishing hype from reality -- Or what history can teach us**

The AI winter of the early 90s was not a result of slow research progress or poor results, but rather the result of hype and overselling of AI in popular media. The hype in the press in the 80s sparkled public curiosity but also led to unfounded and overly optimistic predictions by observers. AI researchers tried to warn the business community and the media about the over-inflated promises and high expectations, but the hype continued, leading to disappointment, disillusionment and ultimately reduced research funding for AI.

Today, we are undergoing an AI spring, with increased AI funding, commercial uptake, public interest and enthusiasm in the media. AI researchers, including researchers in AI in Medicine, have raised concerns around unrealistic promises and expectations, and have warned that a new AI winter might be triggered. Let's see what the future brings\...

\

### **Bonus Content: The State of Artificial Intelligence in Medicine**

Watch the following optional video by Stanford Medicine to find out what experts in AI in Medicine think about the present and future of this field.

<https://youtu.be/PZQMyj-9z-w>

\

------------------------------------------------------------------------
