---
title: "Analysing Clinical Text"
format: html
---

## **Overview**

There is a large volume of health data captured in natural language (e.g. in clinical notes and referral letters), but its computer-based analysis is not that straightforward. In this topic you will be introduced to natural language processing, which is a subfield of linguistics, computer science, information engineering, and artificial intelligence, concerned with how to program computers to process and analyse large amounts of natural language data. You will learn about key tasks in natural language processing and computational methods used. 

Natural Language Processing: Key Tasks and Computational Methods

Watch the following 3 videos to learn about examples of natural language data in the health sector, and to find out more about the area of natural language processing, and the computational methods used for key tasks.

<https://media.ed.ac.uk/media/1_ontbog3b>

[Link](files/Introduction_to_Clinical_Text.docx) to transcript

<https://media.ed.ac.uk/media/1_g6xre2mi>

[Link](files/Natural_Language_Processing_Tasks.docx) to transcript

<https://media.ed.ac.uk/media/1_fpyoqqki>

[Link](files/Methods_for_Analysing_Clinical_Text.docx) to transcript
