---
title: "Reading: COVID and cause of death"
format: html
---

The required pre-reading for this session will be:

**Armstrong D. (2021).** The COVID-19 pandemic and cause of death. *Sociology of health & illness*, *43*(7), 1614–1626. [https://doi.org/10.1111/1467-9566.13347](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1111%2F1467-9566.13347&data=05%7C02%7C%7C6e50c9b168e540dbae9408dcfdb17704%7C2e9f06b016694589878910a06934dc61%7C0%7C0%7C638664185869763626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=I1JU5MOAYpS%2FOzW7JlNptJ49gMHwvlzmyWqolC22W4I%3D&reserved=0)

<a href="files/Armstrong_2021.pdf " target="_blank"> Armstrong_2021.pdf </a>

***And here is a prompt from Dr Perry, to guide your reading:***

In this article, sociologist David Armstrong discusses, the complexity of death attribution – specifically during the covid 19 pandemic. A time, lest we forget, when ‘science’, ‘data’, and the very existence of a pandemic at all was subject to intense public scrutiny. He does this through an inquiry that foregrounds the sociology and the history of death certificates in the production of data.

I think the article is nicely written, but those new to social sciences might find it a little dense. Keep in mind that Armstrong is trying to show the importance of the various social realities that shape the production of data. That is, try to think about the complex and often fraught ways in which, seemingly ‘solid’ data are constructed.

A foundation of ‘evidence-based medicine’ is that medical data will guide us to more precise, and safer medicine. This article shows that even seemingly straight forward knowledge claims based upon healthcare data “how many people have died  *of* covid-19” can be tricky.

Note how Armstrong shows that a decision was made to reorganise the ways that deaths were recorded in order that death certificates would produce more data about deaths with covid. Think about how such decisions are made, and according to what logics? Unchanged, the data would show that covid-19 was having a negligible effect on mortality. Does this change the way we think about the data we are using to know about the world? Should it? As we get and use more and more data do the processes that shape its production grow more or less important?
