---
title: "Week 1 Quiz: Health Data Science Introduction"
format: html
---

Welcome to the Week 1 Quiz! Select the best answer for each question. Good luck!

1.  **Which of the following statements about the data science process is correct?**

-   [ ] Cleaning data is only rarely part of the data science process.
-   [ ] Data analysis is the final phase of the data science process.
-   [ ] The data science process is linear.
-   [ ] The data science process may be repeated several times throughout a project.

2. **You have been provided with access to a large and complex dataset around COVID-19, and you have been asked to use data science methods to predict the number of COVID-19 cases in the UK in two weeks’ time. Which of the following statements is correct?**

-   [ ] Descriptive analytics is all that is needed in this data science project.
-   [ ] Analysing data to predict what will happen in the future is only one of many steps in this data science project.
-   [ ] There is no need to explore the data as part of this data science project.
-   [ ] You should make sure you clean the data only after you have built your predictive model.

3. **Which of the following is NOT typically considered health data?**

-   [ ] Data about a patient’s medical history.
-   [ ] Hospital visit records.
-   [ ] Social media posts.
-   [ ] Weather forecasts

4. **What are Projects in RStudio useful for?**

-  [ ] Great way of helping you to keep all your analysis files together so that R can access them easily.
-  [ ] They will automatically generate a website for you.
-  [ ] They are a way of sharing your code with others.
-  [ ] A project is a place where you can store all of your data analysis projects.

5. **What is the # symbol for in R code?**

-   [ ] It tells R that you are creating a variable.
-   [ ] It's an assignment operator.
-   [ ] It's used to indicate a comment in the code.
-   [ ] It's used to indicate a function in the code. 

6. **What is RMarkdown?**

-   [ ] An alternative to RStudio.
-   [ ] A type of data file used to store large datasets.
-   [ ] A programming language to ensure your analysis is not reproducible.
-   [ ] A file format and a tool which combines both R code and Markdown.

7. **What is the purpose of YAML in an RMarkdown file?**

-  [ ] It's used to create meaningful metadata.
-  [ ] It's used to share your code with others.
-  [ ] It's used to create interactive visualisations.
-  [ ] It's used to store your analysis in a portable format.

------------------------------------------------------------------------
