---
title: "Data and Identity - readings"
format: html
---

The collection, analysis and use of data is political. The effects of knowledge, power and history on data practices are most apparent when they intersect with the lives and experiences of people from minoritised communities, such as LGBTQ communities.

Data practices that involve counting, categorising and managing identity categories (e.g. gender, race and sexuality) are increasingly common in health/science contexts. Numerical identity data provides an evidence base for targeted interventions, community engagement exercises, recruitment and training programmes, and other diversity, equity and inclusion interventions. Our lives are increasingly shaped by how it is defined, collected and used. But who counts in the collection, analysis and application of data?

Drawing from ideas in critical race and gender studies, sociology, history, philosophy and science and technology studies, this session examines the intersection of data practices and identity categories in health/science contexts.

[Required Readings]{.underline}

Guyan, Kevin. *Queer Data: Using Gender, Sex and Sexuality Data for Action*. Bloomsbury Studies in Digital Cultures. London: Bloomsbury Academic, 2022. Introduction: Data and Difference.

Epstein, Steven. *Inclusion: The Politics of Difference in Medical Research*. Chicago: University of Chicago Press, 2007. Introduction: Health Research and the Remaking of Common Sense

<a href="files/Chapter by Kevin Guyan.pdf" target="_blank"> Chapter by Kevin Guyan (PDF) </a>

<a href="files/Chapter%20by%20Steven%20Epstein.pdf" target="_blank"> Chapter by Steven Epstein (PDF) </a>

*Optional readings:*

Cross, Harry, Stephen Bremner, Catherine Meads, Alex Pollard, and Carrie Llewellyn. “Bisexual People Experience Worse Health Outcomes in England: Evidence from a Cross-Sectional Survey in Primary Care.” *The Journal of Sex Research*, July 24, 2023, 1–9. [https://doi.org/10.1080/00224499.2023.2220680](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1080%2F00224499.2023.2220680&data=05%7C02%7C%7Cc026cb5f1ca6435e942408dcccb504c0%7C2e9f06b016694589878910a06934dc61%7C0%7C0%7C638610325072101605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=XRmh8prBLcKcDQujZPI6dPyi0HjsH%2BUGd8nbeDj2btg%3D&reserved=0).

Guyan, Kevin. “Constructing a Queer Population? Asking about Sexual Orientation in Scotland’s 2022 Census.” *Journal of Gender Studies*, January 4, 2021, 1–11. [https://doi.org/10.1080/09589236.2020.1866513](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1080%2F09589236.2020.1866513&data=05%7C02%7C%7Cc026cb5f1ca6435e942408dcccb504c0%7C2e9f06b016694589878910a06934dc61%7C0%7C0%7C638610325072117805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=HWG5ka13eOEOBpkStuoz7%2B53GI0kLjtis6x1ERAaUEI%3D&reserved=0).

Lockhart, Jeffrey W. “Because the Machine Can Discriminate: How Machine Learning Serves and Transforms Biological Explanations of Human Difference.” *Big Data & Society* 10, no. 1 (January 2023): 205395172311550. <https://doi.org/10.1177/20539517231155060>.

Ritz, Stacey A., and Greaves, Lorraine. "More nuanced approaches to exploring sex and gender are warranted." *Nature,* May 2, 2024, 34-36. <https://doi-org.eux.idm.oclc.org/10.1038/d41586-024-01204-3>

Urwin, Sean, Thomas Mason, and William Whittaker. “Do Different Means of Recording Sexual Orientation Affect Its Relationship with Health and Wellbeing?” *Health Economics* 30, no. 12 (December 2021): 3106–22. [https://doi.org/10.1002/hec.4422](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1002%2Fhec.4422&data=05%7C02%7C%7Cc026cb5f1ca6435e942408dcccb504c0%7C2e9f06b016694589878910a06934dc61%7C0%7C0%7C638610325072145459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=OB0w%2Fkz8YupCANcUqh0bITYVx%2FoOuGy1yh6p2Ax%2ByfY%3D&reserved=0).
