---
title: "Computational Methods for Improving Healthcare Processes"
format: html
---

## **Overview**

What is process modelling, and how can one use process modelling methods to gain insight into care pathways, hospital practices and other important processes in healthcare? In this topic you will be introduced to some of the most popular languages for modelling healthcare processes, you will learn how simulation and verification techniques can be used to inform healthcare process improvement initiatives, and you will find out about recent developments around mining health processes from data.

## **Modelling, Analysing and Discovering Healthcare Processes**

Watch the following 4 videos to find out what computational methods can be used to model healthcare processes, to analyse them and to automatically discovering them based on existing data.

<https://media.ed.ac.uk/media/1_eirigrks>

[Link](files/Introduction_to_Healthcare_Processes.docx) to the transcript

<https://media.ed.ac.uk/media/1_act9hmop>

[Link](files/Modelling_Processes.docx) to the transcript

<https://media.ed.ac.uk/media/1_egrcbvzy>

[Link](files/Analysing_Processes.docx) to the transcript

<https://media.ed.ac.uk/media/1_i881krdz>

[Link](files/Process_Mining.docx) to the transcript

------------------------------------------------------------------------
