---
title: "assessment-and-submission-details"
format: html
---

This component of assessment is worth 30% of the overall course mark.

The deadline to submit your final essay is 2nd December 2024 \@ 13:00.

All in course assessments should be submitted to the drop box on Learn.

Work submitted after the deadline will be subject to penalties. All written work will be submitted to a plagiarism check.

The essay topic and brief is available below.

::: text-center
## Data Science for Health and Biomedical Sciences

Ethics essay brief 2025/26
:::

**Essay topic**: Unpack the proposition “Data Saves Lives”. Critically examine the origins of this phrase, using examples to support it, but also critical perspectives from the guest lectures in the course. Consider what forms of value are being created when data are collected and/or analysed, and to whom the value is flowing. Ensure your discussion is well informed by course content (particularly the guest lectures), published literature and current references. If appropriate, add links, figures or quotes, using the Harvard referencing style.

The maximum word count for essays is 1200 words. The word limit for the essay does not include figure legends, tables or the final reference list, but does include in-text citations, headings and subheadings. Please include a final word count on the essay cover sheet. Any essay longer than 1200 words will be marked subject to the BMS word limit policy.

Your assignment should have a cover page with your title, exam number, and word count.

The assessment criteria are available in the Course Handbook.
