---
title: "Assessment and Feedback Information"
format: html
---

#### **Assessment Description**

|                                        |                          |
|----------------------------------------|--------------------------|
| Assessment Type                        | Percentage of Final Mark |
| Coursework - R Programming Assignment  | 70%                      |
| Coursework - Essay                     | 30%                      |

#### **Important Dates**

R Programming Assignment submission - 25 November 2024 \@ 13:00

Essay submission - 2 December 2024 \@ 13:00

#### **Feedback and Grades**

Students will be invited to complete a weekly formative quiz, and will be provided feedback on this.

Students will also be given an opportunity to submit a draft of one section of the assessment (data visualisation), and will receive tutor feedback on this work.

Finally, tutorial classes will be structured to allow students to ask questions, and gain feedback on the data interpretation skills that they will develop throughout the course.

Please be aware that grades located within Learn are provisional until these have been confirmed by the exam board, at which point they will be available via EUCLID.

Dates for the return of provisional marks and feedback will be published in course documentation and will normally be within 3 weeks of the submission deadline. In some cases the feedback return date may be later, for example, if different groups of students have different submission deadlines for the same assignment. In such cases course documentation will still inform you of the date to expect provisional marks and feedback. Please be aware that the marking for all assessments is moderated to ensure consistency and marks and this affects the marking timeline. Marks released remain provisional until they are ratified in by the Board of Examiners meeting after the course finishes. Occasionally, this may result in changes to the provisional marks.

#### **Marking Scheme**

-   [University's Common Marking Scheme](https://edin.ac/common-marking-scheme) (Opens in a new window).

-   [Assessment regulations](https://edin.ac/assessment-regulations) (Opens in a new window).

#### [**Late Submission Penalties**](https://ultra.content.blackboardcdn.com/ultra/uiv3900.116.0-rel.25_2e18a76#)

##### **(a) Word Limits and Word Counts**

1.  Penalties for exceeding the word limit

Where an absolute word limit is specified in assessment documentation the following penalties will be applied if the word limit is exceeded.

-   Exceeding word count by ≤ 10%: 10% deduction of the maximum mark or a reduction to the minimum pass mark for the assessment, whichever results in the higher mark.

-   Exceeding word count by \>10% and ≤ 20%: 20% deduction of the maximum mark or a reduction to the minimum pass mark for the assessment, whichever results in the higher mark.

-   Exceeding word count by \> 20%: mark reduced to the minimum pass mark for the assessment.

##### **(b) What is and is not included in the word limit.**

-   When evaluating the word count it does not include the assessment title, table of contents, references, text in figures, text in tables, table and figure titles, table and figure legends, a list of abbreviations or any acknowledgements.

-   The word limit does include in-text citations (where Harvard referencing is required), headings and sub-headings.

-   The use of appendices is not an allowable mechanism for exceeding the maximum word limit. Therefore, unless otherwise stated in the assessment guidance, material included in an appendix will be regarded as non-assessable and will not be considered by the markers/examiners when arriving at a final mark.

##### **(c) Additional Guidance: Figures and Table With regard to words in figure and / or diagram legends, a figure legend is primarily descriptive of the contents of the figure. The legend must not be used to introduce new**

-   data or information not referred to in the main text of the assessment. Tables should be used to summarise several pieces of information in a succinct and easily approachable manner. As such, figure legends that go beyond the description of figure contents and unnecessarily extensive tables will not be regarded favourably by markers.

Attempts to deliberately circumvent the word limit through, for example,inappropriate hyphenation, including blocks of text as picture images, etc., will be regarded as potential academic misconduct and referred to the Deanery Academic Misconduct Officer.

##### **(d) How the policy will be applied.**

-   Students will be required to indicate the total word count on the assessment cover sheet. Where a word limit is specified, word counts will be checked by the course administrator by opening submissions in MS Word and removing all sections not included in the final word limit. The word count then specified in MS Word will be taken as the final word count.

NOTE: If you experience problems uploading your document, do not panic; simply send the file directly to the Course Administrator ([stewart3.smith\@ed.ac.uk](mailto:stewart3.smith@ed.ac.uk)). The sent date and time on your email will be taken as the time of submission.

**Note that any submissions made after the return of feedback dates will not be marked.**

##### [**Course Work Extensions and Exceptional Circumstances**](https://ultra.content.blackboardcdn.com/ultra/uiv3900.116.0-rel.25_2e18a76#)

For students who need to request an extension for in-course assessments, or need to apply for exceptional circumstances, please refer to the 'Help and Support' section on Learn for further details. Note that the maximum period for eligible course assessments is 4 days.

##### [**Help and Support**](https://ultra.content.blackboardcdn.com/ultra/uiv3900.116.0-rel.25_2e18a76#)

Links to University Systems, BMTO Polices & Guidance and Central University Support can be found in the Help and Support section of Learn.
