---
title: "Further Optional Resources"
format: html
---

[Data Saves Lives](https://datasaveslives.eu/) is a European initiative with the aim of raising awareness about the importance of health data, improving understanding of how it is used and establishing a trusted environment for multi-stakeholder dialogue about responsible use and good practices across Europe. Check out their website for interesting case studies and surveys about public opinions and behaviour around health data.

[The Topol Review](https://topol.hee.nhs.uk/the-topol-review/) was an independent report published in 2019, outlining recommendations to ensure the NHS is the world leader in using digital technologies to benefit patients. This informed look into the future discusses among others, the major impact that genomics is going to have on patient care, as well as how the healthcare workforce can be to prepared deliver the digital future.

[The NHS, AI and Our Data](https://www.bbc.co.uk/programmes/m000dyc2) is an episode of the BBC Radio 4 programme "Analysis", providing an overview of data in the NHS, describing how it is already transforming healthcare, and discussing privacy and other risks.
