---
title: "Overview"
format: html
---

Welcome to the course! This week you will be introduced to key concepts in health data science. We’ll also cover basic R operators and an intro to RMarkdown. You will also get to know your classmates and your lecturer in the live sessions on Thursday and Friday.

## Learning Outcomes

**By the end of the week you will be able to:**

1.  Describe different examples of data in healthcare

2.  Summarise key phases in the data science process

3.  Use some basic R functions

4.  Know what RMarkdown is

5.  Understand how to approach errors in code

#### **Structure of this week's materials**

1.  Introduction to Health Data Science: 2 videos, 1 reading

2.  Role of Ethics in Health and Social Care: 1 reading 

3.  Getting started with R: 1 video, 1 reading, 5 code samples, 4 practice questions

4.  Types of Health Data: 1 reading with code samples

5.  Guide to R Markdown: 1 reading with RStudio examples

<<<<<<< HEAD
6.  Troubleshooting and Error Messages:
=======
6.  Troubleshooting and Error Messages: 1 reading
>>>>>>> d7a2152d2b962cb8b934421f1ed0189140cbaf52
