---
title: "Tutorial Materials"
format: html
---

During this course, it's recommended that you create a directory somewhere on your computer to store all the tutorial materials. You can call it whatever you like, but for the sake of simplicity, we recommend you create the directory on your Desktop and call it `data_science` (no spaces in the name!).

## Thursday

### 1. Bingo!

### 2. Introduction ([introduction.pptx](/tutorials/week-1/introduction.pptx))

### 3. Assessment brief

### 4. Pair programming demo

### 5. Quiz

### 6. BRFSS Analysis (Behavioral Risk Factor Surveillance System)

The goals of this exercise are:

-   Practice pair programming
-   Solve some problems using your current R knowledge (no Tidyverse!)

Create a `New project` called `brfss_analysis` in your `data_science` directory. Save the starter file provided below in `brfss_analysis`.

Remember, you can use the R documentation to help you solve the exercises or Google it!

```{r}
#| echo: false
library(downloadthis)

download_link(
  link = "/tutorials/week-1/1_brfss_analysis.Rmd",
  button_label = "Download the starter file",
  button_type = "danger",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)
```

## Friday

### 1. Updating R, RStudio, installing Tidyverse

### 2. 
