---
title: "Week 1 Tutorial Materials"
format: html
---

## Thursday

At the first lab, there will be a few demonstrations, games and discussions. You won't need to do any programming yourself yet.

## Friday

Today, you will be working on exercise sets in your pairs. But first, we will guide you to create a tidy folder structure for use in the course.

**Step 1:** Create a folder for everything related to this course. You may have a folder like that already - you can use that. If you don't have one yet, create it and call it `data-science`. Remember not to use spaces in file or folder names - they become problematic when we use scripts.

**Step 2:** Now, we will create a subfolder to put the course materials - they will be copied over from a site called GitHub, which the course team will update with new content every week. To do this, open RStudio. Click on `File > New Project > Version Control > Git`. A dialogue window will open. In the Repository URL field, paste https://github.com/DDI-Talent/data-science-for-health-bms-STUDENT-2526.git Press the Tab key, so that the Project directory field gets filled automatically with `data-science-for-health-bms-STUDENT-2526`. Then, in the Create project as a subdirectory of field, ensure that you have chosen the `data-science` folder. You may have to change the thing that your computer put there as default. This process is called "cloning" a repository.

**Step 3:** If everything went well, your `data-science-for-health-bms-STUDENT-2526` folder should now contain a few files: one .Rproj file and a few .Rmd files. 

**Step 4:** In future weeks, you will run the `RUN_TO_GET_RECENT_NOTES.Rmd` file to get the most recent exercises from us. This is not necessary today, because you have just cloned the repository and have the most recent files already there.

**Step 5:** Now, in your `data-science` folder, create a subfolder called `week01`. Copy the exercise sets from `data-science-for-health-bms-STUDENT-2526` into `week1`. You will be working in the `week01` folder, and you will leave the files in `data-science-for-health-bms-STUDENT-2526` untouched. Each week, you will create a new subfolder within `data-science`, and you will copy the relevant files there, so you can work on them. 

**Step 6:** To make navigation easier, you will want to have an R project associated with each week's subfolder. To do this for week 1, go to RStudio and click on `File > New Project > Existing Directory`. In the dialogue window, navigate to the `week01` folder. This will create an RProject associated with that folder.

**Step 7:** When opening exercise sets to work on, the best way is to navigate to the appropriate folder, and then double click on the project file. This will take you to the project's directory in RStudio. You can confirm what project you're working on by checking the project name in the top-right corner of your RStudio window.



